data_util = require("__Krastorio2__/data-util")
require("compatibility.updates")
require("compatibility.aai-industry")
require("compatibility.aai-vehicles-miner")
require("compatibility.aai-vehicles-hauler")
require("compatibility.aai-vehicles-chaingunner")
require("compatibility.aai-vehicles-warden")
require("compatibility.aai-vehicles-flame-tumbler")
require("compatibility.aai-vehicles-flame-tank")
require("compatibility.aai-vehicles-laser-tank")
require("compatibility.aai-vehicles-ironclad")
require("compatibility.ironclad-gunboat")
require("compatibility.hovercrafts")
require("compatibility.cargo-ships")
require("compatibility.clean-trains")
require("compatibility.equipment-gantry")
